version: '3.9'

services:
  web:
    build: .
    container_name: rwebley-website
    volumes:
      - .:/app
      - /home/application_files/newsite/settings.ini:/app/config/settings.ini
    ports:
      - "9000:8000"

